name: Testování

on:
  push:
    branch: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ["prod", "p10"]
    steps:
    - name: Test1
      run: echo "Toto je test 1" 
    - name: Test2
      run: echo "Toto je test 2"
